on:
  push:
    branches:
      - main

jobs:
  linter:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install flake8
      - name: Run Flake8
        run: flake8 ./app --max-line-length=120

  build:
    runs-on: self-hosted
    steps:
      - name: Create .env file
        run: |
          echo "REDIS_DIALOG_HOST=${{ secrets.REDIS_DIALOG_HOST }}" > data
          echo "REDIS_DIALOG_LOGIN=${{ secrets.REDIS_DIALOG_LOGIN }}" >> data
          echo "REDIS_DIALOG_PORT=${{ secrets.REDIS_DIALOG_PORT }}" >> data
          echo "REDIS_DIALOG_PASSWORD=${{ secrets.REDIS_DIALOG_PASSWORD }}" >> data
          echo "REDIS_DIALOG_DB=${{ secrets.REDIS_DIALOG_DB }}" >> data

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: >
          docker build -t ${{ github.event.repository.name }}:latest .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Remove old container
        run: docker rm -f ${{ github.event.repository.name }}

      - name: Run a command inside the container
        run: docker run -d -v data:/usr/src/.env --name ${{ github.event.repository.name }} ${{ github.event.repository.name }}:latest